# Generated by Django 5.0.6 on 2025-03-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fileupload_file_upload_specialfield_special_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileanswer',
            name='ResponseText',
        ),
        migrations.RemoveField(
            model_name='fileanswer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='rangeanswer',
            name='ResponseText',
        ),
        migrations.RemoveField(
            model_name='rangeanswer',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='responsetext',
            name='form',
        ),
        migrations.RemoveField(
            model_name='responsetext',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='ResponseText',
        ),
        migrations.RemoveField(
            model_name='textanswer',
            name='content_type',
        ),
        migrations.DeleteModel(
            name='ChoiceAnswer',
        ),
        migrations.DeleteModel(
            name='FileAnswer',
        ),
        migrations.DeleteModel(
            name='RangeAnswer',
        ),
        migrations.DeleteModel(
            name='ResponseText',
        ),
        migrations.DeleteModel(
            name='TextAnswer',
        ),
    ]
